# Introduction to NumPy


Before reading this introduction you should know a bit of:
1. Python - look at [official tutorial](https://docs.python.org/3/tutorial/)
2. Linear Algebra and Matrices - look at [Coursera tutorial](https://www.coursera.org/learn/linear-algebra-machine-learning) and/or book [Introduction to Applied Linear Algebra](http://vmls-book.stanford.edu/vmls.pdf)

<hr> 

From offical NumPy page we could read that 
```
NumPy is the fundamental package for scientific computing with Python. It contains among other things:
 * a powerful N-dimensional array object
 * useful linear algebra, Fourier transform, and random number capabilities
 * sophisticated (broadcasting) functions
 * tools for integrating C/C++ and Fortran code 
```

All of that functionalities are very useful if you want to do Machine Learning using **CPU**. To install NumPy package, go to [link](https://scipy.org/install.html). There are also very good tutorials:
* [Official NumPy tutorial](https://numpy.org/devdocs/user/quickstart.html)
* [From Python to Numpy](https://www.labri.fr/perso/nrougier/from-python-to-numpy/) 

Here we want give you a quick crash course of using NumPy library.

## Basics: creating a numpy array 

Important notes:
* all items in NumPy array (a.k.a. `ndarray`) cantain only one data type e.g. `int8`, `float32`, ... ([all datatypes](https://numpy.org/devdocs/user/basics.types.html))
* you cannot modify NumPy array

In [0]:
import numpy as np # there is a convention to always import numpy as `np`


print("1d NumPy array from Python list (with `int32` type)")
list1d = [0, 1, 2, 3, 4, 5, 6, 7]
ndarray1d = np.array(list1d, dtype='int32') 
print(ndarray1d) # print ndarray
print(ndarray1d.shape) # print ndarray shape
print()

print("2d NumPy array from Python list of lists  (with `float32` type)")
list2d = [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15]]
ndarray2d = np.array(list2d, dtype='float32')
print(ndarray2d) # print ndarray
print(ndarray2d.shape) # print ndarray shape
print()

print("1d random array (with `float32` type)")
ndarray1d_random = np.random.rand(8, 2).astype('float32')
print(ndarray1d_random) # print ndarray
print(ndarray1d_random.shape) # print ndarray shape
print()

print("1d array with uniform distribution")
ndarray1d_uniform = np.random.uniform(-10, 10, 16)
print(ndarray1d_uniform) # print ndarray
print(ndarray1d_uniform.shape) # print ndarray shape
print()

print("1d array based on linearly spaced vector")
ndarray1d_linspace = np.linspace(0, 7, num=8, dtype='int8')
print(ndarray1d_linspace) # print ndarray
print(ndarray1d_linspace.shape) # print ndarray shape
print()

print("1d array based on `arange` mechanism")
ndarray1d_arange = np.arange(0, 10, 3)
print(ndarray1d_arange) # print ndarray
print(ndarray1d_arange.shape) # print ndarray shape
print()

print("2d zeros array")
ndarray2d_zeros = np.zeros([2, 4])
print(ndarray2d_zeros) # print ndarray
print(ndarray2d_zeros.shape) # print ndarray shape
print()

print("2d ones array")
ndarray2d_ones = np.ones([2, 4])
print(ndarray2d_ones) # print ndarray
print(ndarray2d_ones.shape) # print ndarray shape
print()

1d NumPy array from Python list (with `int32` type)
[0 1 2 3 4 5 6 7]
(8,)

2d NumPy array from Python list of lists  (with `float32` type)
[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]
 [12. 13.]
 [14. 15.]]
(8, 2)

1d random array (with `float32` type)
[[0.07929848 0.04646103]
 [0.13551946 0.09415994]
 [0.31865713 0.7731082 ]
 [0.17045486 0.6933958 ]
 [0.09345574 0.99480355]
 [0.6637033  0.32966194]
 [0.72250724 0.711149  ]
 [0.9396972  0.8823931 ]]
(8, 2)

1d array with uniform distribution
[-7.02870666  7.86882401  9.65007187 -7.83166989 -2.72224666  5.57936585
 -5.10631165 -9.66892718  3.56747523 -7.68795799 -1.05204412  6.419049
 -5.60641786 -2.30801985 -9.21079302 -4.18085661]
(16,)

1d array based on linearly spaced vector
[0 1 2 3 4 5 6 7]
(8,)

1d array based on `arange` mechanism
[0 3 6 9]
(4,)

2d zeros array
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(2, 4)

2d ones array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(2, 4)



## Basics: extracting specific values from ndarrays

Important notes:
* ndarrays can be indexed using the standard Python x[obj] syntax, wherea x is the array and obj the selection, see more at [NumPy indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

In [0]:
print("Get specific element")
print(ndarray2d[1,1])
print()

print("The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step")
print(ndarray1d[0:6:2])
print()

print("Extract only one dimension from multidimensional ndarray") 
print(ndarray2d[:, 0])
print()

print("Boolean array indexing") 
print(ndarray1d[([True, False, True, False, True, False, True, False])])
print()

print("Using condition statement for indexing array") 
print(ndarray1d[(ndarray1d % 2 == 0)]) 
print()

Get specific element
3.0

The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step
[0 2 4]

Extract only one dimension from multidimensional ndarray
[ 0.  2.  4.  6.  8. 10. 12. 14.]

Boolean array indexing
[0 2 4 6]

Using condition statement for indexing array
[0 2 4 6]



## Basics: sum, min, max, mean, reshape 


In [0]:
print("represent `not a number value`")
print(np.nan)
print()

print("represent `infinite`")
print(np.inf)
print()

print("calculate mean, max and min in ndarray")
print("sum ", ndarray2d.sum())
print("max ", ndarray2d.max())
print("min ", ndarray2d.min())
print("mean ", ndarray2d.mean())
print()

print("calculate max on different axis")
print("column max: ", np.max(ndarray2d, axis=0))
print("row max: ", np.max(ndarray2d, axis=1))
print()

print("reshape 2d ndarray")
print(ndarray2d.reshape(4, 4))
print(ndarray2d.shape, ndarray2d.reshape(4, 4).shape)
print()

represent `not a number value`
nan

represent `infinite`
inf

calculate mean, max and min in ndarray
sum  120.0
max  15.0
min  0.0
mean  7.5

calculate max on different axis
column max:  [14. 15.]
row max:  [ 1.  3.  5.  7.  9. 11. 13. 15.]

reshape 2d ndarray
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
(8, 2) (4, 4)



## Basics: array math


In [0]:
print("Initialize NumPy array, x1")
x1 = np.ones([3, 3], dtype='float32')
x1[:, 0] = [2, 3, 4]
print(x1)
print()

print("Transpose x1 array")
print(x1.T)
print()

print("Multiply by scalar, x2=x1*3")
x2 = x1*3.
print(x2)
print()

print("Element-wise sum, x1+x2")
print(x1+x2)
print()

print("Element-wise subtract, x1-x2")
print(x1-x2)
print()

print("Element-wise product, x1*x2")
print(x1*x2)
print()

print("Element-wise divide, x1/x2")
print(x1/x2)
print()

print("Element-wise power, x2^2")
print(np.power(x2, 2))
print()

print("Element-wise square root, sqrt(x2)")
print(np.sqrt(x2))
print()

print("Matrix multiplication, x1*x2")
print(x1.dot(x2))
print()

print("Vector multiplication, x1*x2[0]")
print(x1.dot(x2[0]))
print()

Initialize NumPy array, x1
[[2. 1. 1.]
 [3. 1. 1.]
 [4. 1. 1.]]

Transpose x1 array
[[2. 3. 4.]
 [1. 1. 1.]
 [1. 1. 1.]]

Multiply by scalar, x2=x1*3
[[ 6.  3.  3.]
 [ 9.  3.  3.]
 [12.  3.  3.]]

Element-wise sum, x1+x2
[[ 8.  4.  4.]
 [12.  4.  4.]
 [16.  4.  4.]]

Element-wise subtract, x1-x2
[[-4. -2. -2.]
 [-6. -2. -2.]
 [-8. -2. -2.]]

Element-wise product, x1*x2
[[12.  3.  3.]
 [27.  3.  3.]
 [48.  3.  3.]]

Element-wise divide, x1/x2
[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]]

Element-wise power, x2^2
[[ 36.   9.   9.]
 [ 81.   9.   9.]
 [144.   9.   9.]]

Element-wise square root, sqrt(x2)
[[2.4494898 1.7320508 1.7320508]
 [3.        1.7320508 1.7320508]
 [3.4641016 1.7320508 1.7320508]]

Matrix multiplication, x1*x2
[[33. 12. 12.]
 [39. 15. 15.]
 [45. 18. 18.]]

Vector multiplication, x1*x2[0]
[18. 24. 30.]



## Advanced: broadcasting

Broadcasting allows universal functions to deal in a meaningful way with inputs that do not have exactly the same shape (see more at [this link](https://numpy.org/deavdocs/user/basics.broadcasting.html))

In [0]:
print("Add vector x2 to each row of matrix x1 using broadcasting mechanism")
x1 = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15]])
x2 = np.array([1, 3])
print(x1+x2)

Add vector x2 to each row of matrix x1 using broadcasting mechanism
[[ 1  4]
 [ 3  6]
 [ 5  8]
 [ 7 10]
 [ 9 12]
 [11 14]
 [13 16]
 [15 18]]
