# Introduction to PyTorch

Before reading this introduction you should know a bit of:
1. Python - look at [official tutorial](https://docs.python.org/3/tutorial/)
2. Linear Algebra and Matrices - look at [Coursera tutorial](https://www.coursera.org/learn/linear-algebra-machine-learning) and/or book [Introduction to Applied Linear Algebra](http://vmls-book.stanford.edu/vmls.pdf)



<hr>


From official NumPy page we could read that

```
PyTorch is a Python-based scientific computing package targeted at two sets of audiences:

* A replacement for NumPy to use the power of GPUs
* a deep learning research platform that provides maximum flexibility and speed
```

Contrary to NumPy, PyTorch was designed mostly to work on **GPU**. PyTorch represents n-dimensional array object as  `Tensor`. To install PyTorch library, go to [link](https://pytorch.org/get-started/locally/). There are also very good tutorials:
* [Official PyTorch tutorials](https://pytorch.org/tutorials/)
* [Deep Learning for Natural Language Processing with Pytorch](https://github.com/rguthrie3/DeepLearningForNLPInPytorch/blob/master/Deep%20Learning%20for%20Natural%20Language%20Processing%20with%20Pytorch.ipynb) 

Here we want give you a quick crash course of using PyTorch library, especially Tensor object. 

## Basics: creating a PyTorch tensor

Important notes:
* all items in PyTorch array (a.k.a. `Tensor`) cantain only one data type e.g. `int8`, `float32`, ... ([all datatypes](https://pytorch.org/docs/stable/tensors.html))

In [0]:
import torch 

print("1d Tensor from Python list (with `int32` type)")
list1d = [0, 1, 2, 3, 4, 5, 6, 7]
tensor1d = torch.tensor(list1d, dtype=torch.int32) 
print(tensor1d) # print tensor
print(tensor1d.size()) # print tensor shape
print()

print("2d Tensor from Python list of lists  (with `float32` type)")
list2d = [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15]]
tensor2d = torch.tensor(list2d, dtype=torch.float32)
print(tensor2d) # print tensor
print(tensor2d.size()) # print tensor shape
print()

print("1d random tensor (with `float32` type)")
tensor1d_random = torch.rand(8, 2, dtype=torch.float32)
print(tensor1d_random) # print tensor
print(tensor1d_random.size()) # print tensor shape
print()

print("1d tensor with uniform distribution")
tensor1d_uniform = torch.FloatTensor(16, 1).uniform_(-10, 10)
print(tensor1d_uniform) # print tensor
print(tensor1d_uniform.size()) # print tensor shape
print()

print("1d tensor based on linearly spaced vector")
tensor1d_linspace = torch.linspace(0, 7, steps=8, dtype=torch.float32)
print(tensor1d_linspace) # print tensor
print(tensor1d_linspace.size()) # print tensor shape
print()

print("1d tensor based on `arange` mechanism")
tensor1d_arange = torch.arange(0, 10, 3)
print(tensor1d_arange) # print tensor
print(tensor1d_arange.size()) # print tensor shape
print()

print("2d zeros tensor")
torch2d_zeros = torch.zeros([2, 4])
print(torch2d_zeros) # print tensor
print(torch2d_zeros.size()) # print tensor shape
print()

print("2d ones tensor")
torch2d_ones = torch.ones([2, 4])
print(torch2d_ones) # print tensor
print(torch2d_ones.size()) # print tensor shape
print()

1d Tensor from Python list (with `int32` type)
tensor([0, 1, 2, 3, 4, 5, 6, 7], dtype=torch.int32)
torch.Size([8])

2d Tensor from Python list of lists  (with `float32` type)
tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]])
torch.Size([8, 2])

1d random tensor (with `float32` type)
tensor([[0.2339, 0.1720],
        [0.7893, 0.9454],
        [0.3148, 0.3166],
        [0.7262, 0.8609],
        [0.0912, 0.0767],
        [0.5113, 0.8339],
        [0.7812, 0.9421],
        [0.1299, 0.1272]])
torch.Size([8, 2])

1d tensor with uniform distribution
tensor([[-6.8103],
        [ 0.8485],
        [ 6.5259],
        [ 2.5182],
        [ 0.6380],
        [-3.1469],
        [-3.4691],
        [ 4.6706],
        [ 2.0206],
        [-8.8526],
        [-3.8986],
        [ 0.9371],
        [-9.4456],
        [-8.4750],
        [-1.1130],
        [ 3.2142]])
torch.Size([16, 1])

1d tensor base

## Basics: extracting specific values from tensors

Important notes:
* tensor can be indexed using the standard Python x[obj] syntax, wherea x is the array and obj the selection

In [0]:
print("Get specific element")
print(tensor2d[1,1])
print()

print("The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step")
print(tensor1d[0:6:2])
print()

print("Extract only one dimension from multidimensional ndarray") 
print(tensor2d[:, 0])
print()

print("Boolean array indexing") 
print(tensor1d[([True, False, True, False, True, False, True, False])])
print()

print("Using condition statement for indexing array") 
print(tensor1d[(tensor1d % 2 == 0)]) 
print()

Get specific element
tensor(3.)

The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step
tensor([0, 2, 4], dtype=torch.int32)

Extract only one dimension from multidimensional ndarray
tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

Boolean array indexing
tensor([0, 2, 4, 6], dtype=torch.int32)

Using condition statement for indexing array
tensor([0, 2, 4, 6], dtype=torch.int32)



## Basics: sum, min, max, mean, reshape 

In [0]:
print("represent `not a number value`")
print(torch.tensor(float('nan')))
print()

print("represent `infinite`")
print(torch.tensor(float('Inf')))
print()

print("calculate mean, max and min in tensor")
print("sum ", tensor2d.sum())
print("max ", tensor2d.max())
print("min ", tensor2d.min())
print("mean ", tensor2d.mean())
print()

print("calculate max on different axis")
print("column max: ", tensor2d.max(dim=0)[0])
print("row max: ", tensor2d.max(dim=1)[0])
print()

print("reshape 2d tensor")
print(tensor2d.view(4, 4))
print(tensor2d.size(), tensor2d.view(4, 4).size())
print()

print("reshape 2d tensor (second way)")
print(tensor2d.view(4, -1)) # the second dimention is adjusted to size of the matrix
print(tensor2d.size(), tensor2d.view(4, -1).size())
print()

represent `not a number value`
tensor(nan)

represent `infinite`
tensor(inf)

calculate mean, max and min in tensor
sum  tensor(120.)
max  tensor(15.)
min  tensor(0.)
mean  tensor(7.5000)

calculate max on different axis
column max:  tensor([14., 15.])
row max:  tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15.])

reshape 2d tensor
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
torch.Size([8, 2]) torch.Size([4, 4])

reshape 2d tensor (second way)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
torch.Size([8, 2]) torch.Size([4, 4])



## Basics: tensor math

In [0]:
print("Initialize tensor, x1")
x1 = torch.ones([3, 3], dtype=torch.float32)
x1[:, 0] = torch.tensor([2., 3., 4.])
print(x1)
print()

print("Transpose x1 tensor")
print(x1.transpose(0, 1))
print()

print("Multiply by scalar, x2=x1*3")
x2 = x1*3.
print(x2)
print()

print("Element-wise sum, x1+x2")
print(x1+x2)
print()

print("Element-wise subtract, x1-x2")
print(x1-x2)
print()

print("Element-wise product, x1*x2")
print(x1*x2)
print()

print("Element-wise divide, x1/x2")
print(x1/x2)
print()

print("Element-wise power, x2^2")
print(torch.pow(x2, 2))
print()

print("Element-wise square root, sqrt(x2)")
print(torch.sqrt(x2))
print()

print("Matrix multiplication, x1*x2")
print(x1.mm(x2))
print()

print("Vector multiplication, x1*x2[0]")
print(x1.mm(x2[0].view([-1, 1])).view(-1))
print()

Initialize tensor, x1
tensor([[2., 1., 1.],
        [3., 1., 1.],
        [4., 1., 1.]])

Transpose x1 tensor
tensor([[2., 3., 4.],
        [1., 1., 1.],
        [1., 1., 1.]])

Multiply by scalar, x2=x1*3
tensor([[ 6.,  3.,  3.],
        [ 9.,  3.,  3.],
        [12.,  3.,  3.]])

Element-wise sum, x1+x2
tensor([[ 8.,  4.,  4.],
        [12.,  4.,  4.],
        [16.,  4.,  4.]])

Element-wise subtract, x1-x2
tensor([[-4., -2., -2.],
        [-6., -2., -2.],
        [-8., -2., -2.]])

Element-wise product, x1*x2
tensor([[12.,  3.,  3.],
        [27.,  3.,  3.],
        [48.,  3.,  3.]])

Element-wise divide, x1/x2
tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])

Element-wise power, x2^2
tensor([[ 36.,   9.,   9.],
        [ 81.,   9.,   9.],
        [144.,   9.,   9.]])

Element-wise square root, sqrt(x2)
tensor([[2.4495, 1.7321, 1.7321],
        [3.0000, 1.7321, 1.7321],
        [3.4641, 1.7321, 1.7321]])

Matrix multiplication, x

## Advanced: broadcasting

In short, if a PyTorch operation supports broadcast, then its Tensor arguments can be automatically expanded to be of equal sizes (see more at [this link](https://pytorch.org/docs/stable/notes/broadcasting.html))

In [0]:
print("Add vector x2 to each row of matrix x1 using broadcasting mechanism")
x1 = torch.tensor([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15]])
x2 = torch.tensor([1, 3])
print(x1+x2)

Add vector x2 to each row of matrix x1 using broadcasting mechanism
tensor([[ 1,  4],
        [ 3,  6],
        [ 5,  8],
        [ 7, 10],
        [ 9, 12],
        [11, 14],
        [13, 16],
        [15, 18]])
